### ISSUE TITLE
chart index problem 

### ISSUE THREAD

**Issue by WBSON** [sunspec/svp_energy_lab#22]
I notice that a chart in the result excel file may have a problem. 
For axis Y1, the chart draws data from index 2, but for axis Y2, the chart seems draw data from index 3.

In the excel file, for Y1 the command is 
"=SERIES("U1",voltage_trip_p1_1.csv!$A$2:$A$1002,voltage_trip_p1_1.csv!$B$2:$B$1002,1)", 
and for Y2 the command is 
"=SERIES("I1",voltage_trip_p1_1.csv!$A$2:$A$1002,voltage_trip_p1_1.csv!$E$3:$E$1002,2)"

**Comment by EstefanCanmet** [comment]
I didn't have a feedback from other but it looks similar to the issue #17 .

I gave a [solution ](https://github.com/sunspec/svp_energy_lab/issues/17#issuecomment-447017384) that worked for me.

Let me know if it works for you !

**Comment by WBSON** [comment]
It was an indexing bug in "add_chart" method in "ResultWorkbook" class.
I update the result.py to fix it.
